### ISSUE TITLE
刚刚运行就报bug

### ISSUE THREAD

**Issue by Johnjson** [BCsl/CursorWheelLayout#1]
FATAL EXCEPTION: main
                                                                                   Process: github.hellocsl.cursorwheellayout, PID: 20584
                                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{github.hellocsl.cursorwheellayout/github.hellocsl.cursorwheellayout.MainActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class github.hellocsl.cursorwheellayout.widget.SimpleTextCursorWheelLayout
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
                                                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:141)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                                    Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class github.hellocsl.cursorwheellayout.widget.SimpleTextCursorWheelLayout
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:775)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:358)
                                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                       at github.hellocsl.cursorwheellayout.MainActivity.onCreate(MainActivity.java:38)
                                                                                       at android.app.Activity.performCreate(Activity.java:5302)
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
                                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                                       at github.hellocsl.cursorwheellayout.MainActivity.onCreate(MainActivity.java:38) 
                                                                                       at android.app.Activity.performCreate(Activity.java:5302) 
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                                    Caused by: java.lang.NoSuchMethodError: android.view.ViewGroup.<init>
                                                                                       at github.hellocsl.cursorwheel.CursorWheelLayout.<init>(CursorWheelLayout.java:214)
                                                                                       at github.hellocsl.cursorwheel.CursorWheelLayout.<init>(CursorWheelLayout.java:209)
                                                                                       at github.hellocsl.cursorwheel.CursorWheelLayout.<init>(CursorWheelLayout.java:205)
                                                                                       at github.hellocsl.cursorwheellayout.widget.SimpleTextCursorWheelLayout.<init>(SimpleTextCursorWheelLayout.java:19)
                                                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
                                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                                       at github.hellocsl.cursorwheellayout.MainActivity.onCreate(MainActivity.java:38) 
                                                                                       at android.app.Activity.performCreate(Activity.java:5302) 
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5336) 
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by BCsl** [comment]
github.hellocsl.cursorwheellayout.widget.SimpleTextCursorWheelLayout 这个是我再DEMO的一个实现类，如果你没实现自己的，就不需要这样用，应该是使用这个github.hellocsl.cursorwheel.CursorWheelLayout
