### ISSUE TITLE
java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by moelfassi** [BCsl/CursorWheelLayout#5]
Hi,

I'm using this Library in a fragment:

` 

```
       <github.hellocsl.cursorwheel.CursorWheelLayout

        android:id="@+id/circle_menu"
        android:layout_width="300dip"
        android:layout_height="300dip"
        android:layout_gravity="right|bottom"
        android:layout_marginBottom="-120dp"
        android:layout_marginRight="-120dip"
        app:wheelBackgroundColor="@color/pink"
        app:wheelCursorColor="@color/red"
        app:wheelCursorHeight="20dip"
        app:wheelFlingValue="460"
        app:wheelSelectedAngle="225">


        <ImageView
            android:id="@id/id_wheel_menu_center_item"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:src="@drawable/car"
            android:textColor="#009688"
            />

    </github.hellocsl.cursorwheel.CursorWheelLayout>`
```

but i've an exception:

`java.lang.ArithmeticException: divide by zero
                                                                          at github.hellocsl.cursorwheel.CursorWheelLayout.onLayout(CursorWheelLayout.java:362)
                                                                          at android.view.View.layout(View.java:16637)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at android.view.View.layout(View.java:16637)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                          at android.view.View.layout(View.java:16637)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
                                                                          at android.view.View.layout(View.java:16637)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at android.view.View.layout(View.java:16637)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                          at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
                                                                          at android.view.View.layout(View.java:16637)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at android.view.View.layout(View.java:16637)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
                                                                          at android.view.View.layout(View.java:16637)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
                                                                          at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1724)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1490)
                                                                          at android.view.View.layout(View.java:16637)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                          at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1187)
                                                                          at android.view.View.layout(View.java:16637)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                          at android.view.View.layout(View.java:16637)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                          at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2179)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1939)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6029)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Thank you

**Comment by BCsl** [comment]
did you only set the center item and without menu items?

**Comment by moelfassi** [comment]
i have "menu items" using an adapter

**Comment by BCsl** [comment]
Can you post your code here?

**Comment by BCsl** [comment]
I don't thank it could throw  divide by zero exception when menu items is not empty and you can try to  debug with this exception for what went wrong.

**Comment by up2marius** [comment]
I am having this issue also.
